name: "🚀 Feature Request"
description: "Décrire une nouvelle fonctionnalité sous forme de User Story"
title: "[FR] "
labels: ["feature"]
assignees: []

body:
  - type: textarea
    id: user-story
    attributes:
      label: "⭐ User Story"
      description: "Décris ta demande sous forme de User Story"
      value: |
        As a [role],
        I want [an action or feature],
        So that [a reason or benefit].
    validations:
      required: true

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: "🌟 Acceptance Criteria"
      description: "Coche les critères qui définissent la complétion"
      options:
        - label: "Criteria 1: Describe the first acceptance criterion here"
        - label: "Criteria 2: Describe the second acceptance criterion here"
        - label: "Criteria 3: Add additional criteria as needed"

  - type: checkboxes
    id: definition-of-done
    attributes:
      label: "✅ Definition of Done"
      description: "Coche quand la feature est prête"
      options:
        - label: "All acceptance criteria are met"
        - label: "Code is reviewed and approved"
        - label: "Necessary tests are written and pass"
        - label: "Documentation is updated, if applicable"
        - label: "Feature is deployed to the [environment name]"
